app: 
  name: "bluebell"
  mode: "dev"
  port: 8080
  start_time: "2020-07-01"
  machine_id: 1

log: 
  level: "debug"
  output: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 5
  compress: false

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "zy20050608"
  dbname: "bluebell"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10