app: 
  name: "web_app"
  mode: "dev"
  port: 8081

log: 
  leverl: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 5
  compress: false

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "web_app"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10